name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 12

      - run: yarn
      - run: (cd example && yarn)

#      - uses: mxschmitt/action-tmate@v3

      - run: npm test

      - if: github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: example/build
